[package]
name = "metapartition"
version = "0.1.0"
edition = "2021"

[features]
default = []
hmetis = ["dep:hmetis_r"]

[dependencies]
kahypar_r = { git = "https://github.com/profmadden/kahypar_r" }
hmetis_r =  {optional = true, git = "https://github.com/profmadden/hmetis_r"}
